### PR TITLE
slim down docker image

### PR DESCRIPTION
**Pull request by bclermont**
If you're interested to release a smaller docker image.

### CODE REVIEW

**Comment by Niondir** [comment]
Basically a smaller image is nice. But this way we would need a go installation on the root system. I like to avoid that dependency. We could just remove golang and all unnecessary files from the container after building resitc to slim down the container.

Another point is that the run script got a little bit complex. I prefer a simple setup via docker-compose.

**Comment by bclermont** [comment]
> Basically a smaller image is nice. But this way we would need a go installation on the root system.

only the host that build the image need Go installation, not the docker host that run it

like https://github.com/restic/restic/pull/1061/files#diff-c0d65d2fb9fff450085d1f1a44ca5bb1R6

**Comment by bclermont** [comment]
> Basically a smaller image is nice. But this way we would need a go installation on the root system.

only the host that build the image need Go installation, not the docker host that run it.

**Comment by Niondir** [comment]
Yea right. Currently I rely on https://hub.docker.com - They just build the Docker file as far as I see. Or is there any way to build the container via the `build.sh` script on docker hub?

**Pull request closed without merging**
